// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Controls: typeof import('./components/Controls.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    PaperCard: typeof import('./components/PaperCard.vue')['default']
    PaperList: typeof import('./components/PaperList.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VisCard: typeof import('./components/VisCard.vue')['default']
    VisList: typeof import('./components/VisList.vue')['default']
  }
}

export {}
